"""批量列表与条目卡片样式。"""

from __future__ import annotations

from ._hex_helper import _hex_to_rgba
from .design_tokens import Border, Radius, Spacing, Typography
from .theme_semantics import (
    COLOR_DANGER,
    COLOR_SECONDARY,
    COLOR_WARNING,
    is_dark_theme,
)


def build_batch_list_stylesheet(theme_name: str, font_size_preset: str | None = None) -> str:
    """批量列表与条目卡片样式统一收口到全局主题中心。"""
    dark_theme = is_dark_theme(theme_name)
    warning_hint_color = _hex_to_rgba(COLOR_WARNING, 168 if dark_theme else 128)
    detail_hint_color = _hex_to_rgba(COLOR_SECONDARY, 168 if dark_theme else 104)
    danger_hint_color = _hex_to_rgba(COLOR_DANGER, 176 if dark_theme else 134)
    return "\n".join(
        [
            "/* docwen-batch-list-foundation */",
            # -- Surface --
            "QWidget#batchListSurface {",
            f"    border: {Border.THIN}px solid palette(midlight);",
            f"    border-radius: {Radius.LARGE}px;",
            "    background: palette(base);",
            "}",
            "QFrame#batchListSummarySection,",
            "QFrame#batchListTabsFrame {",
            f"    border: {Border.THIN}px solid palette(midlight);",
            f"    border-radius: {Radius.MEDIUM}px;",
            "    background: palette(alternate-base);",
            "}",
            "QFrame#batchListSummarySection {",
            f"    padding: {Spacing.SM}px;",
            "}",
            "QFrame#batchListSummaryHeader {",
            "    background: transparent;",
            "}",
            "QLabel#batchListSummaryLabel {",
            "    background: transparent;",
            "    font-weight: 500;",
            f"    line-height: {Spacing.LG}px;",
            "}",
            "QPushButton#batchFilterButton,",
            "QPushButton#batchSortButton,",
            "QPushButton#batchReorderButton {",
            f"    border-radius: {Radius.MEDIUM}px;",
            f"    padding-left: {Spacing.XS}px;",
            f"    padding-right: {Spacing.XS}px;",
            f"    font-size: {Typography.qss(Typography.CAPTION_SIZE, font_size_preset)};",
            "}",
            "QPushButton#batchFilterButton:hover,",
            "QPushButton#batchSortButton:hover,",
            "QPushButton#batchReorderButton:hover {",
            "    background: palette(base);",
            "}",
            "QFrame#batchListTabsFrame QWidget#batchCategoryPivot {",
            "    background: transparent;",
            "}",
            'QWidget#batchCategoryPivot QPushButton[hasContent="false"] {',
            "    color: palette(mid);",
            "}",
            'QWidget#batchCategoryPivot QPushButton[hasContent="true"][isCurrentRoute="false"] {',
            "    color: palette(text);",
            "}",
            'QWidget#batchCategoryPivot QPushButton[isCurrentRoute="true"] {',
            "    color: palette(highlight);",
            "    font-weight: 600;",
            f"    border-bottom: {Border.THIN}px solid palette(highlight);",
            "}",
            "QStackedWidget#batchCategoryStack {",
            "    background: transparent;",
            "    border: none;",
            "}",
            "QListWidget#batchListWidget {",
            "    border: none;",
            "    background: transparent;",
            f"    padding: {Spacing.XS}px;",
            "}",
            "QListWidget#batchListWidget:focus {",
            f"    border: {Border.THIN}px solid palette(highlight);",
            f"    border-radius: {Radius.MEDIUM}px;",
            "    background: palette(base);",
            "}",
            "QListWidget#batchListWidget::item {",
            "    border: none;",
            "    padding: 0px;",
            f"    margin-bottom: {Spacing.SM}px;",
            "}",
            "QWidget#batchEntryCard {",
            f"    border: {Border.THIN}px solid palette(mid);",
            f"    border-radius: {Radius.DEFAULT}px;",
            "    background-color: palette(base);",
            "}",
            'QWidget#batchEntryCard[stateHovered="true"] {',
            "    border-color: palette(midlight);",
            "    background-color: palette(window);",
            "}",
            'QWidget#batchEntryCard[stateSelected="true"] {',
            "    border-color: palette(highlight);",
            "    background-color: palette(alternate-base);",
            "}",
            'QWidget#batchEntryCard[stateCurrent="true"] {',
            "    border-color: palette(highlight);",
            "}",
            'QWidget#batchEntryCard[stateSelected="true"] QWidget#batchHeaderRow,',
            'QWidget#batchEntryCard[stateCurrent="true"] QWidget#batchHeaderRow {',
            "    border-bottom-color: palette(highlight);",
            "}",
            "QWidget#batchHeaderRow {",
            "    background: transparent;",
            f"    border-bottom: {Border.THIN}px solid palette(midlight);",
            "    padding-bottom: 2px;",
            "}",
            "QWidget#batchBadgeRow,",
            "QWidget#batchOutputRow,",
            "QWidget#batchInfoRow {",
            "    background: transparent;",
            "}",
            "QLabel#batchEntryName {",
            "    background: transparent;",
            "    font-weight: 600;",
            "}",
            "QWidget#batchBodySection {",
            "    background: transparent;",
            "}",
            "QWidget#batchBodySection {",
            f"    border-top: {Border.THIN}px solid palette(midlight);",
            "    padding-top: 2px;",
            "}",
            "QWidget#batchActionsRow {",
            "    background: transparent;",
            f"    border-top: {Border.THIN}px solid palette(midlight);",
            "    padding-top: 2px;",
            "}",
            'QWidget#batchEntryCard[stateHovered="true"] QWidget#batchBodySection {',
            "    border-top-color: palette(midlight);",
            "}",
            'QWidget#batchEntryCard[stateSelected="true"] QWidget#batchBodySection,',
            'QWidget#batchEntryCard[stateCurrent="true"] QWidget#batchBodySection {',
            "    border-top-color: palette(highlight);",
            "}",
            'QWidget#batchEntryCard[stateHovered="true"] QWidget#batchActionsRow {',
            "    border-top-color: palette(midlight);",
            "}",
            'QWidget#batchEntryCard[stateSelected="true"] QWidget#batchActionsRow,',
            'QWidget#batchEntryCard[stateCurrent="true"] QWidget#batchActionsRow {',
            "    border-top-color: palette(highlight);",
            "}",
            "QWidget#batchOutputRow {",
            f"    border-top: {Border.THIN}px solid palette(midlight);",
            "}",
            "QLabel#batchInfoLabel {",
            "    background: transparent;",
            "    padding-right: 4px;",
            "}",
            'QLabel#batchInfoLabel[class="secondary"] {',
            f"    color: {detail_hint_color};",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "}",
            'QLabel#batchInfoLabel[class="warning"] {',
            f"    color: {warning_hint_color};",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "    font-weight: 600;",
            "}",
            'QLabel#batchInfoLabel[class="danger"] {',
            f"    color: {danger_hint_color};",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "    font-weight: 600;",
            "}",
            # -- Output label + badge --
            "QLabel#batchOutputLabel {",
            "    background: transparent;",
            "    font-weight: 500;",
            "}",
            "QLabel#batchOutputBadge, QLabel#batchBadge {",
            f"    border: {Border.THIN}px solid palette(mid);",
            f"    border-radius: {Radius.SMALL}px;",
            "    padding: 1px 6px;",
            "    background-color: palette(window);",
            "}",
            'QLabel#batchBadge[badgeRole="info"] {',
            "    border-style: dashed;",
            "    background-color: transparent;",
            "    color: palette(text);",
            "    font-weight: 500;",
            "}",
            'QLabel#batchOutputBadge, QLabel#batchBadge[badgeRole="warning"], QLabel#batchBadge[badgeRole="output"] {',
            "    font-weight: 500;",
            "}",
            "QLabel#batchInfoBadge {",
            f"    border: {Border.THIN}px solid palette(mid);",
            f"    border-radius: {Radius.SMALL}px;",
            "    padding: 1px 6px;",
            "    background-color: palette(window);",
            "}",
            # -- Path and detail label colors --
            "QLabel#batchPathLabel, QLabel#batchDetailLabel {",
            "    background: transparent;",
            "}",
            'QLabel#batchPathLabel, QLabel#batchDetailLabel[detailRole="secondary"] {',
            f"    color: {detail_hint_color};",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "}",
            'QLabel#batchPathLabel[interactiveText="true"], QLabel#batchOutputLabel[interactiveText="true"], QLabel#batchDetailLabel[interactiveText="true"] {',
            "    font-weight: 600;",
            "}",
            'QLabel#batchPathLabel[interactiveTextHovered="true"], QLabel#batchOutputLabel[interactiveTextHovered="true"], QLabel#batchDetailLabel[interactiveTextHovered="true"] {',
            "    color: palette(highlight);",
            "}",
            "QLabel#batchPathLabel:focus, QLabel#batchOutputLabel:focus, QLabel#batchDetailLabel:focus {",
            f"    border: {Border.THIN}px solid palette(highlight);",
            f"    border-radius: {Radius.SMALL}px;",
            "    padding: 0 2px;",
            "}",
            # -- Push buttons --
            "QPushButton#batchReorderButton:focus,",
            "QPushButton#batchFilterButton:focus,",
            "QPushButton#batchSortButton:focus,",
            "QPushButton#fileDropPrimaryButton:focus,",
            "QPushButton#fileDropClearButton:focus {",
            f"    border: {Border.THIN}px solid palette(highlight);",
            "    background: palette(base);",
            "}",
            'QPushButton#fileDropClearButton[fileDropTextCollapsed="true"] {',
            "    min-width: 0;",
            f"    padding-left: {Spacing.SM}px;",
            f"    padding-right: {Spacing.SM}px;",
            "}",
        ]
    )
