"""转换面板基础样式。"""

from __future__ import annotations

from .design_tokens import Border, Radius, Spacing, Typography
from .panel_card import build_panel_card_stylesheet
from .theme_semantics import is_dark_theme


def build_conversion_panel_stylesheet(theme_name: str, font_size_preset: str | None = None) -> str:
    """转换面板基础样式。"""
    hint_color = "#CBD5E1" if is_dark_theme(theme_name) else "#475569"
    return "\n".join(
        [
            build_panel_card_stylesheet(font_size_preset),
            "/* docwen-conversion-panel-foundation */",
            "QRadioButton#conversionRadioButton {",
            "    spacing: 8px;",
            "    min-height: 32px;",
            "    color: palette(text);",
            "}",
            "QRadioButton#conversionRadioButton::indicator {",
            "    width: 16px; height: 16px;",
            "    border: 2px solid palette(mid);",
            "    border-radius: 10px;",
            "    background: palette(base);",
            "}",
            "QRadioButton#conversionRadioButton::indicator:checked {",
            "    width: 8px; height: 8px;",
            "    border: 6px solid palette(highlight);",
            "    background: palette(highlighted-text);",
            "}",
            "QRadioButton#conversionRadioButton::indicator:hover,",
            "QRadioButton#conversionRadioButton::indicator:focus {",
            "    border-color: palette(highlight);",
            "}",
            "QWidget#conversionPanelRoot QScrollArea#conversionPanelScrollArea,",
            "QWidget#conversionPanelRoot QWidget#conversionPanelScrollContent {",
            "    border: none;",
            "    background: transparent;",
            "}",
            # -- Subtle divider --
            "QWidget#conversionPanelRoot QFrame#conversionSubtleDivider {",
            "    color: palette(midlight);",
            "    background-color: palette(midlight);",
            "    min-height: 1px;",
            "    max-height: 1px;",
            "    border: none;",
            "}",
            # -- Nested option group --
            "QFrame#conversionOptionGroup {",
            f"    margin-top: {Spacing.XS}px;",
            "}",
            "QWidget#conversionPanelRoot QWidget#conversionOptionRow {",
            "    background: transparent;",
            "}",
            "QLabel#conversionOptionLabel {",
            "    color: palette(text);",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "    font-weight: 600;",
            "}",
            "QWidget#conversionPanelRoot QLabel#hintLabel {",
            f"    color: {hint_color};",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "}",
            "QWidget#conversionPanelRoot QLabel#conversionSectionDescription {",
            f"    color: {hint_color};",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "}",
            "QWidget#conversionPanelRoot QLabel#conversionDetailLabel {",
            f"    color: {hint_color};",
            f"    font-size: {Typography.qss(Typography.CAPTION_SIZE, font_size_preset)};",
            "}",
            "QWidget#conversionPanelRoot QLabel#warningLabel {",
            "    color: palette(text);",
            f"    font-size: {Typography.qss(Typography.CAPTION_SIZE, font_size_preset)};",
            "}",
            "QWidget#conversionPanelRoot QWidget#conversionButtonRow {",
            "    background: transparent;",
            "}",
            "QWidget#conversionPanelRoot QPushButton#conversionSecondaryButton {",
            "    color: palette(text);",
            f"    border: {Border.THIN}px solid palette(midlight);",
            f"    border-radius: {Radius.MEDIUM}px;",
            "    background-color: palette(alternate-base);",
            f"    padding: {Spacing.XS}px {Spacing.MD}px;",
            "}",
            "QWidget#conversionPanelRoot QPushButton#conversionSecondaryButton:hover {",
            "    border-color: palette(highlight);",
            "    background-color: palette(base);",
            "}",
            "QWidget#conversionPanelRoot QPushButton#conversionSecondaryButton:pressed {",
            "    background-color: palette(midlight);",
            "}",
            "QWidget#conversionPanelRoot QPushButton#conversionSecondaryButton:disabled {",
            "    color: palette(mid);",
            f"    border: {Border.THIN}px solid palette(midlight);",
            "    background-color: palette(alternate-base);",
            "}",
            "QWidget#generalTransparencyValueRow {",
            "    background: transparent;",
            "}",
            "QDoubleSpinBox#generalTransparencySpinBox {",
            "    min-width: 92px;",
            "    max-width: 92px;",
            "}",
            "QLabel#generalTransparencyPercentLabel {",
            "    color: palette(mid);",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "    font-weight: 600;",
            "}",
        ]
    )
