"""全局低风险容器统一基础样式。"""

from __future__ import annotations

from ._hex_helper import _hex_to_rgba
from .design_tokens import Border, Radius, Spacing, Typography
from .theme_semantics import (
    COLOR_DANGER,
    COLOR_PRIMARY,
    COLOR_SECONDARY,
    COLOR_WARNING,
    is_dark_theme,
)


def build_panel_stylesheet(theme_name: str, font_size_preset: str | None = None) -> str:
    """为全局低风险容器提供统一基础样式。"""
    dark_theme = is_dark_theme(theme_name)
    section_border = _hex_to_rgba(COLOR_SECONDARY, 128 if dark_theme else 58)
    section_emphasis_border = _hex_to_rgba(COLOR_SECONDARY, 150 if dark_theme else 78)
    section_background = _hex_to_rgba("#111B2E" if dark_theme else "#FFFFFF", 242 if dark_theme else 255)
    section_background_alt = _hex_to_rgba("#0E1728" if dark_theme else "#F8FAFC", 234 if dark_theme else 250)
    field_background = _hex_to_rgba("#182437" if dark_theme else "#FFFFFF", 246 if dark_theme else 255)
    combo_border = _hex_to_rgba(COLOR_SECONDARY, 154 if dark_theme else 76)
    combo_hover_border = _hex_to_rgba(COLOR_SECONDARY, 198 if dark_theme else 112)
    combo_focus_border = _hex_to_rgba(COLOR_PRIMARY, 214 if dark_theme else 168)
    combo_focus_background = _hex_to_rgba("#1F2937" if dark_theme else "#FFFFFF", 248 if dark_theme else 255)
    combo_popup_border = _hex_to_rgba(COLOR_SECONDARY, 168 if dark_theme else 82)
    combo_popup_background = _hex_to_rgba("#111827" if dark_theme else "#FFFFFF", 250 if dark_theme else 255)
    combo_item_hover = _hex_to_rgba(COLOR_PRIMARY, 28 if dark_theme else 18)
    combo_item_selected = _hex_to_rgba(COLOR_PRIMARY, 42 if dark_theme else 28)
    spinbox_button_hover = _hex_to_rgba(COLOR_PRIMARY, 22 if dark_theme else 16)
    spinbox_button_pressed = _hex_to_rgba(COLOR_PRIMARY, 34 if dark_theme else 24)
    spinbox_button_border = _hex_to_rgba(COLOR_SECONDARY, 116 if dark_theme else 54)
    file_drop_selected_border = _hex_to_rgba(COLOR_PRIMARY, 156 if dark_theme else 118)
    file_drop_selected_background = _hex_to_rgba("#172554" if dark_theme else "#EFF6FF", 214 if dark_theme else 248)
    file_drop_drag_border = _hex_to_rgba(COLOR_PRIMARY, 224 if dark_theme else 178)
    file_drop_drag_background = _hex_to_rgba(COLOR_PRIMARY, 36 if dark_theme else 22)
    file_drop_feedback_warning_border = _hex_to_rgba(COLOR_WARNING, 150 if dark_theme else 112)
    file_drop_feedback_warning_background = _hex_to_rgba(
        "#422006" if dark_theme else "#FFFBEB", 214 if dark_theme else 248
    )
    file_drop_feedback_danger_border = _hex_to_rgba(COLOR_DANGER, 156 if dark_theme else 118)
    file_drop_feedback_danger_background = _hex_to_rgba(
        "#450A0A" if dark_theme else "#FEF2F2", 214 if dark_theme else 248
    )
    section_title_color = _hex_to_rgba("#F8FAFC" if dark_theme else "#0F172A", 228 if dark_theme else 188)
    hint_color = _hex_to_rgba("#CBD5E1" if dark_theme else "#475569", 218 if dark_theme else 224)
    warning_hint_color = _hex_to_rgba(COLOR_WARNING, 168 if dark_theme else 128)
    scrollbar_track = _hex_to_rgba("#0F172A" if dark_theme else "#E2E8F0", 88 if dark_theme else 118)
    scrollbar_handle = _hex_to_rgba(COLOR_SECONDARY, 168 if dark_theme else 132)
    scrollbar_handle_hover = _hex_to_rgba(COLOR_PRIMARY, 196 if dark_theme else 154)
    settings_changes_color = _hex_to_rgba("#E2E8F0" if dark_theme else "#334155", 188 if dark_theme else 154)
    subtle_divider = _hex_to_rgba(COLOR_SECONDARY, 110 if dark_theme else 42)
    combo_arrow = (
        ":/qfluentwidgets/images/icons/ChevronDown_white.svg"
        if dark_theme
        else ":/qfluentwidgets/images/icons/ChevronDown_black.svg"
    )

    return "\n".join(
        [
            "/* docwen-global-panel-foundation */",
            # -- Status & about hero cards (grouped with theme preview) --
            "QWidget#aboutHeroCard,",
            # -- Settings cards & sections --
            "QWidget#generalThemePreviewFrame,",
            'QWidget#settingsTabRoot QWidget[settingsRole="settingsCard"] {',
            f"    border: {Border.THIN}px solid {section_border};",
            f"    border-radius: {Radius.LARGE}px;",
            f"    background-color: {section_background};",
            "}",
            "QWidget#settingsTabRoot QGroupBox#settingsSectionGroup,",
            "QWidget#conversionPanelRoot QGroupBox#conversionPrimaryGroup,",
            "QWidget#conversionPanelRoot QGroupBox#conversionSecondaryGroup,",
            "QWidget#conversionPanelRoot QGroupBox#conversionExtraGroup {",
            f"    border-radius: {Radius.LARGE}px;",
            "}",
            "QWidget#settingsTabRoot QGroupBox#settingsSectionGroup::title,",
            "QWidget#conversionPanelRoot QGroupBox::title,",
            "QLabel#generalThemePreviewTitle,",
            "QLabel#settingsCardTitle {",
            f"    color: {section_title_color};",
            "    font-weight: 600;",
            f"    font-size: {Typography.qss(Typography.CARD_TITLE_SIZE, font_size_preset)};",
            "}",
            "QLabel#hintLabel,",
            "QLabel#generalLanguageHint,",
            "QLabel#settingsCardDescription {",
            f"    color: {hint_color};",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "}",
            "QWidget#settingsTabRoot QGroupBox#settingsSectionGroup {",
            f"    border: {Border.THIN}px solid {section_border};",
            f"    background-color: {section_background};",
            "}",
            "QWidget#conversionPanelRoot QGroupBox#conversionPrimaryGroup {",
            f"    border: {Border.THIN}px solid {section_emphasis_border};",
            f"    background-color: {section_background};",
            "}",
            "QWidget#conversionPanelRoot QGroupBox#conversionSecondaryGroup,",
            "QWidget#conversionPanelRoot QGroupBox#conversionExtraGroup {",
            f"    border: {Border.THIN}px solid {section_border};",
            f"    background-color: {section_background_alt};",
            "}",
            # -- File drop area (InputArea) --
            "QFrame#fileDropGroup {",
            f"    border: {Border.THIN}px solid {section_border};",
            f"    border-radius: {Radius.XL}px;",
            f"    background-color: {section_background_alt};",
            "}",
            'QFrame#fileDropGroup[dropState="selected"] {',
            f"    border-color: {file_drop_selected_border};",
            f"    background-color: {file_drop_selected_background};",
            "}",
            'QFrame#fileDropGroup[dropState="drag-active"] {',
            f"    border-color: {file_drop_drag_border};",
            f"    background-color: {file_drop_drag_background};",
            "}",
            "QFrame#inputArea {",
            "    background: transparent;",
            "}",
            "QLabel#fileDropEyebrowLabel {",
            f"    color: {hint_color};",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "    font-weight: 600;",
            "    padding: 2px 8px;",
            "}",
            "QWidget#fileDropEmptyStateContent {",
            "    background: transparent;",
            "}",
            "QWidget#fileDropEmptyStateCenterPanel {",
            "    background: transparent;",
            "}",
            "QWidget#fileDropEmptyStateTitleRow {",
            "    background: transparent;",
            "}",
            "QLabel#fileDropHeroIconLabel {",
            "    background: transparent;",
            "    border: none;",
            "    padding: 0;",
            "}",
            'QLabel#fileDropHeroIconLabel[heroVariant="symbol"] {',
            f"    border: {Border.THIN}px solid {section_border};",
            "    border-radius: 14px;",
            f"    background-color: {field_background};",
            "    padding: 4px;",
            "}",
            'QFrame#fileDropGroup[dropState="selected"] QLabel#fileDropHeroIconLabel[heroVariant="symbol"],',
            'QFrame#fileDropGroup[dropState="drag-active"] QLabel#fileDropHeroIconLabel[heroVariant="symbol"] {',
            f"    border-color: {file_drop_selected_border};",
            f"    background-color: {field_background};",
            "}",
            "QLabel#fileDropPromptLabel {",
            f"    font-size: {Typography.qss(Typography.HERO_SIZE, font_size_preset)};",
            "    font-weight: 600;",
            "    padding-top: 0;",
            "}",
            "QFrame#fileDropFeedbackFrame {",
            f"    border: {Border.THIN}px solid {section_border};",
            f"    border-radius: {Radius.MEDIUM}px;",
            f"    background-color: {section_background};",
            "}",
            'QFrame#fileDropFeedbackFrame[feedbackTone="success"] {',
            f"    border-color: {file_drop_selected_border};",
            f"    background-color: {file_drop_selected_background};",
            "}",
            'QFrame#fileDropFeedbackFrame[feedbackTone="warning"] {',
            f"    border-color: {file_drop_feedback_warning_border};",
            f"    background-color: {file_drop_feedback_warning_background};",
            "}",
            'QFrame#fileDropFeedbackFrame[feedbackTone="danger"] {',
            f"    border-color: {file_drop_feedback_danger_border};",
            f"    background-color: {file_drop_feedback_danger_background};",
            "}",
            "QLabel#fileDropFeedbackTitleLabel {",
            f"    color: {hint_color};",
            "    font-weight: 600;",
            "}",
            'QFrame#fileDropFeedbackFrame[feedbackTone="warning"] QLabel#fileDropFeedbackTitleLabel {',
            f"    color: {warning_hint_color};",
            "}",
            'QFrame#fileDropFeedbackFrame[feedbackTone="danger"] QLabel#fileDropFeedbackTitleLabel {',
            f"    color: {warning_hint_color};",
            "}",
            "QLabel#fileDropSelectionLabel {",
            "    color: palette(text);",
            "    padding-top: 0;",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "}",
            "QLabel#fileDropSelectionDetailLabel {",
            f"    color: {hint_color};",
            "    padding-top: 0;",
            f"    font-size: {Typography.qss(Typography.CAPTION_SIZE, font_size_preset)};",
            "}",
            # -- File drop type labels --
            "QWidget#fileDropTypesContainer, QWidget#fileDropTypesRow {",
            "    background: transparent;",
            "}",
            "QLabel#fileDropTypesTypeLabel, QLabel#fileDropTypesValueLabel {",
            f"    color: {hint_color};",
            f"    font-size: {Typography.qss(Typography.CAPTION_SIZE, font_size_preset)};",
            "}",
            "QLabel#fileDropTypesTypeLabel {",
            "    font-weight: 600;",
            "}",
            # -- Settings dialog shared elements --
            "QDialog#settingsDialog QLabel#settingsStatusLabel {",
            f"    border: {Border.THIN}px solid {section_border};",
            f"    border-radius: {Radius.MEDIUM}px;",
            f"    background-color: {field_background};",
            f"    padding: {Spacing.XS}px {Spacing.SM}px;",
            "}",
            "QDialog#settingsDialog QLabel#settingsChangesLabel {",
            "    border: none;",
            "    background: transparent;",
            f"    color: {settings_changes_color};",
            f"    padding: 0 {Spacing.XS}px;",
            "}",
            "QWidget#generalThemePreviewFrame {",
            f"    background-color: {field_background};",
            "}",
            "QLabel#generalThemePreviewButton {",
            f"    border: {Border.THIN}px solid {section_border};",
            "    border-radius: 999px;",
            "    padding: 4px 10px;",
            "    background: transparent;",
            "    font-weight: 600;",
            "}",
            # -- Generic form controls --
            "QComboBox, QAbstractSpinBox {",
            f"    background-color: {field_background};",
            "}",
            "QLineEdit, QTextEdit, QPlainTextEdit {",
            f"    padding: {Spacing.XS}px {Spacing.SM + 2}px;",
            f"    border: {Border.THIN}px solid {combo_border};",
            f"    border-radius: {Radius.MEDIUM}px;",
            f"    background-color: {field_background};",
            "    selection-background-color: palette(highlight);",
            "}",
            "QLineEdit:hover, QTextEdit:hover, QPlainTextEdit:hover {",
            f"    border-color: {combo_hover_border};",
            "}",
            "QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {",
            f"    border-color: {combo_focus_border};",
            f"    background-color: {combo_focus_background};",
            "}",
            "QLineEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled {",
            f"    border-color: {section_border};",
            f"    background-color: {section_background_alt};",
            f"    color: {hint_color};",
            "}",
            "QComboBox {",
            f"    padding: {Spacing.XS}px {Spacing.XL + 8}px {Spacing.XS}px {Spacing.SM + 2}px;",
            f"    border: {Border.THIN}px solid {combo_border};",
            f"    border-radius: {Radius.MEDIUM}px;",
            "}",
            "QComboBox:hover {",
            f"    border-color: {combo_hover_border};",
            "}",
            "QComboBox:focus,",
            "QComboBox:on {",
            f"    border-color: {combo_focus_border};",
            f"    background-color: {combo_focus_background};",
            "}",
            "QComboBox::drop-down {",
            "    border: none;",
            "    background: transparent;",
            "    width: 30px;",
            "}",
            "QComboBox:left-to-right::drop-down {",
            f"    border-left: {Border.THIN}px solid {spinbox_button_border};",
            "}",
            "QComboBox:right-to-left::drop-down {",
            f"    border-right: {Border.THIN}px solid {spinbox_button_border};",
            "}",
            "QComboBox::drop-down:hover {",
            f"    background-color: {spinbox_button_hover};",
            "}",
            "QComboBox::drop-down:pressed, QComboBox::drop-down:on {",
            f"    background-color: {spinbox_button_pressed};",
            "}",
            "QComboBox::down-arrow {",
            f"    image: url({combo_arrow});",
            "    width: 12px;",
            "    height: 12px;",
            "}",
            "QComboBox:disabled {",
            f"    border-color: {section_border};",
            f"    background-color: {section_background_alt};",
            f"    color: {hint_color};",
            "}",
            "QComboBox QAbstractItemView {",
            f"    border: {Border.THIN}px solid {combo_popup_border};",
            f"    border-radius: {Radius.MEDIUM}px;",
            f"    background-color: {combo_popup_background};",
            "    outline: 0;",
            f"    padding: {Spacing.XS}px;",
            f"    selection-background-color: {combo_item_selected};",
            "}",
            "QComboBox QAbstractItemView::item {",
            f"    min-height: {Spacing.LG + 10}px;",
            f"    padding: {Spacing.XS}px {Spacing.SM}px;",
            f"    border-radius: {Radius.SMALL}px;",
            "}",
            "QComboBox QAbstractItemView::item:hover {",
            f"    background-color: {combo_item_hover};",
            "}",
            "QComboBox QAbstractItemView::item:selected {",
            f"    background-color: {combo_item_selected};",
            "}",
            "QAbstractSpinBox {",
            f"    padding: {Spacing.XS}px {Spacing.XL + 10}px {Spacing.XS}px {Spacing.SM + 2}px;",
            f"    border: {Border.THIN}px solid {combo_border};",
            f"    border-radius: {Radius.MEDIUM}px;",
            "}",
            "QAbstractSpinBox:hover {",
            f"    border-color: {combo_hover_border};",
            "}",
            "QAbstractSpinBox:focus {",
            f"    border-color: {combo_focus_border};",
            f"    background-color: {combo_focus_background};",
            "}",
            "QAbstractSpinBox::up-button,",
            "QAbstractSpinBox::down-button {",
            "    subcontrol-origin: border;",
            f"    width: {Spacing.LG + 10}px;",
            f"    border-left: {Border.THIN}px solid {spinbox_button_border};",
            "    background: transparent;",
            "}",
            "QAbstractSpinBox::up-button:hover,",
            "QAbstractSpinBox::down-button:hover {",
            f"    background-color: {spinbox_button_hover};",
            "}",
            "QAbstractSpinBox::up-button:pressed,",
            "QAbstractSpinBox::down-button:pressed {",
            f"    background-color: {spinbox_button_pressed};",
            "}",
            # -- Menus & tooltips --
            "QMenu {",
            f"    border: {Border.THIN}px solid {combo_popup_border};",
            f"    border-radius: {Radius.MEDIUM}px;",
            f"    background-color: {combo_popup_background};",
            f"    padding: {Spacing.XS}px;",
            "}",
            "QMenu::item {",
            f"    padding: {Spacing.XS}px {Spacing.XL}px {Spacing.XS}px {Spacing.SM + 4}px;",
            f"    border-radius: {Radius.SMALL}px;",
            "}",
            "QMenu::item:selected {",
            f"    background-color: {combo_item_selected};",
            "}",
            "QMenu::item:disabled {",
            f"    color: {hint_color};",
            "}",
            "QMenu::separator {",
            "    height: 1px;",
            f"    background: {subtle_divider};",
            f"    margin: {Spacing.XS}px {Spacing.SM}px;",
            "}",
            "QMenu::indicator {",
            "    width: 14px;",
            "    height: 14px;",
            "}",
            "QToolTip {",
            f"    border: {Border.THIN}px solid {combo_popup_border};",
            f"    border-radius: {Radius.SMALL}px;",
            f"    background-color: {combo_popup_background};",
            "    color: palette(text);",
            f"    padding: {Spacing.XS}px {Spacing.SM}px;",
            "}",
            # -- Checkboxes in known containers --
            "QWidget#settingsTabRoot QCheckBox,",
            "QWidget#actionAreaRoot QCheckBox,",
            "QWidget#conversionPanelRoot QCheckBox {",
            f"    spacing: {Spacing.SM}px;",
            "}",
            # -- Scrollbars --
            "QScrollBar:vertical {",
            "    background: transparent;",
            "    width: 12px;",
            "    margin: 4px 2px 4px 2px;",
            "}",
            "QScrollBar::handle:vertical {",
            f"    background-color: {scrollbar_handle};",
            f"    border-radius: {Radius.DEFAULT}px;",
            "    min-height: 28px;",
            "}",
            "QScrollBar::handle:vertical:hover {",
            f"    background-color: {scrollbar_handle_hover};",
            "}",
            "QScrollBar::add-line:vertical,",
            "QScrollBar::sub-line:vertical {",
            "    height: 0px;",
            "    background: transparent;",
            "    border: none;",
            "}",
            "QScrollBar::add-page:vertical,",
            "QScrollBar::sub-page:vertical {",
            f"    background: {scrollbar_track};",
            f"    border-radius: {Radius.DEFAULT}px;",
            "}",
            "QScrollBar:horizontal {",
            "    background: transparent;",
            "    height: 12px;",
            "    margin: 2px 4px 2px 4px;",
            "}",
            "QScrollBar::handle:horizontal {",
            f"    background-color: {scrollbar_handle};",
            f"    border-radius: {Radius.DEFAULT}px;",
            "    min-width: 28px;",
            "}",
            "QScrollBar::handle:horizontal:hover {",
            f"    background-color: {scrollbar_handle_hover};",
            "}",
            "QScrollBar::add-line:horizontal,",
            "QScrollBar::sub-line:horizontal {",
            "    width: 0px;",
            "    background: transparent;",
            "    border: none;",
            "}",
            "QScrollBar::add-page:horizontal,",
            "QScrollBar::sub-page:horizontal {",
            f"    background: {scrollbar_track};",
            f"    border-radius: {Radius.DEFAULT}px;",
            "}",
            # -- GroupBox titles --
            "QWidget#actionAreaRoot QGroupBox::title,",
            "QWidget#settingsTabRoot QGroupBox#settingsSectionGroup::title,",
            "QWidget#conversionPanelRoot QGroupBox::title {",
            "    font-weight: 600;",
            f"    font-size: {Typography.qss(Typography.CARD_TITLE_SIZE, font_size_preset)};",
            "}",
            # -- Action area section styling --
            "QWidget#actionAreaRoot QWidget#actionOptionRow {",
            "    background: transparent;",
            "}",
            # -- Action section divider --
            'QWidget#actionAreaRoot QFrame#actionSectionDividerLine[actionDividerVariant="subtle"] {',
            f"    background: {subtle_divider};",
            "    max-height: 1px;",
            f"    margin: {Spacing.XS}px 0;",
            "    border: none;",
            "}",
        ]
    )
