"""设置页基础样式。"""

from __future__ import annotations

from ._hex_helper import _hex_to_rgba
from .design_tokens import Border, Radius, Spacing, Typography
from .theme_semantics import COLOR_PRIMARY, COLOR_SECONDARY, is_dark_theme


def build_settings_stylesheet(theme_name: str, font_size_preset: str | None = None) -> str:
    """设置页基础样式。"""
    dark_theme = is_dark_theme(theme_name)
    section_title_soft = _hex_to_rgba("#E2E8F0" if dark_theme else "#1E293B", 206 if dark_theme else 164)
    section_description_color = _hex_to_rgba(COLOR_SECONDARY, 186 if dark_theme else 120)
    tab_description_color = _hex_to_rgba("#E2E8F0" if dark_theme else "#334155", 168 if dark_theme else 144)
    secondary_button_text = _hex_to_rgba("#E2E8F0" if dark_theme else "#334155", 188 if dark_theme else 168)
    secondary_button_border = _hex_to_rgba(COLOR_SECONDARY, 124 if dark_theme else 82)
    secondary_button_hover = _hex_to_rgba("#FFFFFF" if dark_theme else "#0F172A", 18 if dark_theme else 6)
    secondary_button_pressed = _hex_to_rgba("#FFFFFF" if dark_theme else "#0F172A", 26 if dark_theme else 10)
    secondary_button_surface = _hex_to_rgba("#1E293B" if dark_theme else "#FFFFFF", 246 if dark_theme else 252)
    disabled_button_text = _hex_to_rgba(COLOR_SECONDARY, 112 if dark_theme else 96)
    return "\n".join(
        [
            "/* docwen-settings-foundation */",
            "QWidget#settingsTabRoot QLabel#settingsTabTitle {",
            "    color: palette(text);",
            f"    font-size: {Typography.qss(Typography.PAGE_TITLE_SIZE, font_size_preset)};",
            "    font-weight: 600;",
            f"    padding: {Spacing.XS}px {Spacing.MD}px 0 {Spacing.MD}px;",
            "}",
            "QDialog#settingsDialog QPushButton#settingsResetTabButton,",
            "QDialog#settingsDialog QPushButton#settingsResetAllButton,",
            "QDialog#settingsDialog QDialogButtonBox {",
            "    spacing: 8px;",
            "}",
            "QDialog#settingsDialog QPushButton#settingsResetTabButton,",
            "QDialog#settingsDialog QPushButton#settingsResetAllButton {",
            "    min-width: 84px;",
            f"    border-radius: {Radius.MEDIUM}px;",
            "}",
            "QDialog#settingsDialog QPushButton#settingsLoggingCopyPathButton,",
            "QDialog#settingsDialog QPushButton#settingsLoggingOpenDirectoryButton,",
            "QDialog#settingsDialog QPushButton#settingsOkButton,",
            "QDialog#settingsDialog QPushButton#settingsCancelButton,",
            "QDialog#settingsDialog QPushButton#settingsApplyButton {",
            "    min-width: 78px;",
            f"    border-radius: {Radius.MEDIUM}px;",
            "}",
            "QDialog#settingsDialog QPushButton#settingsResetTabButton,",
            "QDialog#settingsDialog QPushButton#settingsResetAllButton,",
            "QDialog#settingsDialog QPushButton#settingsLoggingCopyPathButton,",
            "QDialog#settingsDialog QPushButton#settingsLoggingOpenDirectoryButton,",
            "QDialog#settingsDialog QPushButton#settingsCancelButton,",
            "QDialog#settingsDialog QPushButton#settingsApplyButton {",
            f"    color: {secondary_button_text};",
            f"    border: {Border.THIN}px solid {secondary_button_border};",
            "    background: transparent;",
            "    font-weight: 500;",
            "}",
            "QDialog#settingsDialog QPushButton#settingsResetTabButton:hover,",
            "QDialog#settingsDialog QPushButton#settingsResetAllButton:hover,",
            "QDialog#settingsDialog QPushButton#settingsLoggingCopyPathButton:hover,",
            "QDialog#settingsDialog QPushButton#settingsLoggingOpenDirectoryButton:hover,",
            "QDialog#settingsDialog QPushButton#settingsCancelButton:hover,",
            "QDialog#settingsDialog QPushButton#settingsApplyButton:hover {",
            f"    background-color: {secondary_button_hover};",
            f"    border-color: {secondary_button_text};",
            "}",
            "QDialog#settingsDialog QPushButton#settingsResetTabButton:pressed,",
            "QDialog#settingsDialog QPushButton#settingsResetAllButton:pressed,",
            "QDialog#settingsDialog QPushButton#settingsLoggingCopyPathButton:pressed,",
            "QDialog#settingsDialog QPushButton#settingsLoggingOpenDirectoryButton:pressed,",
            "QDialog#settingsDialog QPushButton#settingsCancelButton:pressed,",
            "QDialog#settingsDialog QPushButton#settingsApplyButton:pressed {",
            f"    background-color: {secondary_button_pressed};",
            "}",
            "QDialog#settingsDialog QLabel#settingsStatusLabel,",
            "QDialog#settingsDialog QLabel#settingsChangesLabel {",
            "    margin-top: 2px;",
            "}",
            "QDialog#numberingAddDialog QDialogButtonBox QPushButton,",
            "QDialog#numberingCleanDialog QDialogButtonBox QPushButton,",
            "QDialog#symbolMappingEditor QDialogButtonBox QPushButton,",
            "QDialog#typosDictionaryEditor QDialogButtonBox QPushButton,",
            "QDialog#symbolErrorEditor QDialogButtonBox QPushButton,",
            "QDialog#sensitiveWordEditor QDialogButtonBox QPushButton,",
            "QWidget#tomlEditorDialog QDialogButtonBox QPushButton {",
            "    min-width: 78px;",
            "    min-height: 32px;",
            f"    border-radius: {Radius.MEDIUM}px;",
            "}",
            "QDialog#settingsDialog QPushButton#settingsOkButton {",
            f"    color: {'#F8FAFC' if dark_theme else '#FFFFFF'};",
            f"    background-color: {COLOR_PRIMARY};",
            f"    border: {Border.THIN}px solid {COLOR_PRIMARY};",
            "    font-weight: 600;",
            "}",
            "QDialog#settingsDialog QPushButton#settingsOkButton:hover {",
            f"    background-color: {_hex_to_rgba(COLOR_PRIMARY, 232 if dark_theme else 214)};",
            "}",
            "QDialog#settingsDialog QPushButton#settingsOkButton:pressed {",
            f"    background-color: {_hex_to_rgba(COLOR_PRIMARY, 196 if dark_theme else 184)};",
            "}",
            "QWidget#settingsTabRoot QPushButton,",
            "QDialog#numberingAddDialog QPushButton,",
            "QDialog#numberingCleanDialog QPushButton,",
            "QDialog#symbolMappingEditor QPushButton,",
            "QDialog#typosDictionaryEditor QPushButton,",
            "QDialog#symbolErrorEditor QPushButton,",
            "QDialog#sensitiveWordEditor QPushButton,",
            "QWidget#tomlEditorDialog QPushButton,",
            "QDialog#numberingAddDialog QToolButton {",
            f"    color: {secondary_button_text};",
            f"    border: {Border.THIN}px solid {secondary_button_border};",
            f"    border-radius: {Radius.MEDIUM}px;",
            f"    background-color: {secondary_button_surface};",
            f"    padding: {Spacing.XS}px {Spacing.SM}px;",
            "    min-height: 32px;",
            "}",
            "QWidget#settingsTabRoot QPushButton:hover,",
            "QDialog#numberingAddDialog QPushButton:hover,",
            "QDialog#numberingCleanDialog QPushButton:hover,",
            "QDialog#symbolMappingEditor QPushButton:hover,",
            "QDialog#typosDictionaryEditor QPushButton:hover,",
            "QDialog#symbolErrorEditor QPushButton:hover,",
            "QDialog#sensitiveWordEditor QPushButton:hover,",
            "QWidget#tomlEditorDialog QPushButton:hover,",
            "QDialog#numberingAddDialog QToolButton:hover {",
            f"    background-color: {secondary_button_hover};",
            f"    border-color: {secondary_button_text};",
            "}",
            "QWidget#settingsTabRoot QPushButton:pressed,",
            "QDialog#numberingAddDialog QPushButton:pressed,",
            "QDialog#numberingCleanDialog QPushButton:pressed,",
            "QDialog#symbolMappingEditor QPushButton:pressed,",
            "QDialog#typosDictionaryEditor QPushButton:pressed,",
            "QDialog#symbolErrorEditor QPushButton:pressed,",
            "QDialog#sensitiveWordEditor QPushButton:pressed,",
            "QWidget#tomlEditorDialog QPushButton:pressed,",
            "QDialog#numberingAddDialog QToolButton:pressed {",
            f"    background-color: {secondary_button_pressed};",
            "}",
            "QWidget#settingsTabRoot QPushButton:disabled,",
            "QDialog#numberingAddDialog QPushButton:disabled,",
            "QDialog#numberingCleanDialog QPushButton:disabled,",
            "QDialog#symbolMappingEditor QPushButton:disabled,",
            "QDialog#typosDictionaryEditor QPushButton:disabled,",
            "QDialog#symbolErrorEditor QPushButton:disabled,",
            "QDialog#sensitiveWordEditor QPushButton:disabled,",
            "QWidget#tomlEditorDialog QPushButton:disabled,",
            "QDialog#numberingAddDialog QToolButton:disabled {",
            f"    color: {disabled_button_text};",
            f"    border-color: {_hex_to_rgba(COLOR_SECONDARY, 72 if dark_theme else 48)};",
            "    background-color: transparent;",
            "}",
            "QWidget#settingsTabRoot QScrollArea#settingsTabScrollArea {",
            "    border: none;",
            "    background: transparent;",
            "}",
            "QWidget#settingsTabRoot QWidget#settingsTabScrollContainer {",
            "    background: transparent;",
            "}",
            'QWidget#settingsTabRoot QWidget[settingsRole="settingsCard"] {',
            f"    margin-top: {Spacing.SM}px;",
            "}",
            "QWidget#settingsTabRoot QGroupBox#settingsSectionGroup {",
            f"    border-radius: {Radius.LARGE}px;",
            f"    margin-top: {Spacing.LG}px;",
            f"    padding-top: {Spacing.MD + 2}px;",
            "}",
            "QWidget#settingsTabRoot QGroupBox#settingsSectionGroup::title {",
            "    subcontrol-origin: margin;",
            "    left: 12px;",
            "    padding: 0 4px;",
            "    color: palette(text);",
            "}",
            'QWidget#settingsTabRoot QLabel[settingsRole="fieldLabel"] {',
            f"    color: {section_title_soft};",
            "    font-weight: 600;",
            "}",
            'QWidget#settingsTabRoot QLabel[settingsRole="sectionDescription"] {',
            f"    color: {section_description_color};",
            f"    font-size: {Typography.qss(Typography.BODY_SIZE, font_size_preset)};",
            "}",
            'QWidget#settingsTabRoot QLabel[settingsRole="tabDescription"] {',
            f"    color: {tab_description_color};",
            f"    font-size: {Typography.qss(Typography.CARD_TITLE_SIZE, font_size_preset)};",
            "}",
            "QWidget#settingsTabRoot QLabel#proofreadHintLabel {",
            f"    color: {section_description_color};",
            f"    font-size: {Typography.qss(Typography.CAPTION_SIZE, font_size_preset)};",
            "}",
            "QWidget#settingsTabRoot QCheckBox#settingsToggle {",
            "    spacing: 10px;",
            "    padding: 2px 0;",
            "}",
            "QWidget#settingsTabRoot QLineEdit,",
            "QWidget#settingsTabRoot QTextEdit,",
            "QWidget#settingsTabRoot QPlainTextEdit {",
            "    background-color: transparent;",
            "}",
        ]
    )
