"""Focused tests split from test_markdown_assets.py."""

from __future__ import annotations

from ._markdown_assets_support import (
    Path,
    _build_fake_context,
    _ocr_success,
    pytest,
    tempfile,
)

pytestmark = [pytest.mark.golden, pytest.mark.contract]


class TestImageToMarkdownOcrBlockquoteTitle:
    """F-G1-005, F-G2-003: Verify the OCR blockquote title line is emitted
    when configured by the request-owned OCR title policy."""

    def test_blockquote_title_prepended_when_configured(
        self, sample_png_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """When ``ocr_blockquote_title_override_text`` is set, the generated
        blockquote leads with a bold title line."""
        import docwen_plugin_image.to_markdown.converter as converter_mod
        from docwen_plugin_image.to_markdown.converter import (
            ImageToMarkdownConverter,
        )

        monkeypatch.setattr(converter_mod, "run_ocr_outcome", lambda _path, **_kwargs: _ocr_success("测试文本"))

        with tempfile.TemporaryDirectory() as staging:
            context = _build_fake_context(
                str(sample_png_path),
                staging,
                "md",
                {
                    "image_mode": "file",
                    "ocr_placement": "main_md",
                    "to_md_enable_ocr": True,
                    "to_md_keep_images": True,
                },
                ocr_blockquote_title="识别文字",
            )
            result = ImageToMarkdownConverter().convert(context)

            assert result.success is True
            primary_md = Path(result.artifacts[0].staging_path).read_text(encoding="utf-8")
            # Title line appears before OCR content
            assert "> **识别文字**" in primary_md
            assert "> 测试文本" in primary_md
            # Title line comes before content
            title_pos = primary_md.index("> **识别文字**")
            content_pos = primary_md.index("> 测试文本")
            assert title_pos < content_pos

    def test_blockquote_title_disabled_omits_title(
        self, sample_png_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """When ``ocr_blockquote_title_enabled=False``, no title line is
        prepended."""
        import docwen_plugin_image.to_markdown.converter as converter_mod
        from docwen_plugin_image.to_markdown.converter import (
            ImageToMarkdownConverter,
        )

        monkeypatch.setattr(converter_mod, "run_ocr_outcome", lambda _path, **_kwargs: _ocr_success("测试文本"))

        with tempfile.TemporaryDirectory() as staging:
            context = _build_fake_context(
                str(sample_png_path),
                staging,
                "md",
                {
                    "image_mode": "file",
                    "ocr_placement": "main_md",
                    "to_md_enable_ocr": True,
                    "to_md_keep_images": True,
                },
                ocr_blockquote_title="",
            )
            result = ImageToMarkdownConverter().convert(context)

            assert result.success is True
            primary_md = Path(result.artifacts[0].staging_path).read_text(encoding="utf-8")
            assert "> 测试文本" in primary_md
            assert "> **" not in primary_md  # no bold title

    def test_blockquote_title_in_image_md_auxiliary(
        self, sample_png_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """When ocr_placement_mode=image_md and a blockquote title is set,
        the title appears in the auxiliary .md, not the primary."""
        import docwen_plugin_image.to_markdown.converter as converter_mod
        from docwen_plugin_image.to_markdown.converter import (
            ImageToMarkdownConverter,
        )

        monkeypatch.setattr(converter_mod, "run_ocr_outcome", lambda _path, **_kwargs: _ocr_success("辅助文件OCR"))

        with tempfile.TemporaryDirectory() as staging:
            context = _build_fake_context(
                str(sample_png_path),
                staging,
                "md",
                {
                    "image_mode": "file",
                    "ocr_placement": "image_md",
                    "to_md_enable_ocr": True,
                    "to_md_keep_images": True,
                },
                ocr_blockquote_title="OCR结果",
            )
            result = ImageToMarkdownConverter().convert(context)

            assert result.success is True
            aux = next(a for a in result.artifacts if a.kind == "auxiliary")
            aux_md = Path(aux.staging_path).read_text(encoding="utf-8")
            assert "> **OCR结果**" in aux_md
            assert "> 辅助文件OCR" in aux_md


class TestImageToMarkdownMdFileLinkStyle:
    """F-G1-005, F-G2-003: Verify that .md file links generated by
    ``image_md`` placement respect the configured ``md_file_link_style``."""

    def test_md_file_link_style_wiki_embed(self, sample_png_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Default wiki_embed produces ``![[file.md]]`` for the auxiliary .md."""
        import docwen_plugin_image.to_markdown.converter as converter_mod
        from docwen_plugin_image.to_markdown.converter import (
            ImageToMarkdownConverter,
        )

        monkeypatch.setattr(converter_mod, "run_ocr_outcome", lambda _path, **_kwargs: _ocr_success("wiki嵌入"))

        with tempfile.TemporaryDirectory() as staging:
            context = _build_fake_context(
                str(sample_png_path),
                staging,
                "md",
                {
                    "image_mode": "file",
                    "ocr_placement": "image_md",
                    "to_md_enable_ocr": True,
                    "to_md_keep_images": True,
                },
                config_snapshot={"link": {"format": {"md_file_link_style": "wiki_embed"}}},
            )
            result = ImageToMarkdownConverter().convert(context)

            assert result.success is True
            primary_md = Path(next(a for a in result.artifacts if a.kind == "primary").staging_path).read_text(
                encoding="utf-8"
            )
            assert "![[sample_ocr.md]]" in primary_md
            assert "[[sample_ocr.md]]" in primary_md  # contained within ![[ ]]
            assert "[sample_ocr.md](sample_ocr.md)" not in primary_md

    def test_md_file_link_style_wiki_link(self, sample_png_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """``wiki_link`` produces ``[[file.md]]`` (no ``!``) for the
        auxiliary .md."""
        import docwen_plugin_image.to_markdown.converter as converter_mod
        from docwen_plugin_image.to_markdown.converter import (
            ImageToMarkdownConverter,
        )

        monkeypatch.setattr(converter_mod, "run_ocr_outcome", lambda _path, **_kwargs: _ocr_success("wiki链接"))

        with tempfile.TemporaryDirectory() as staging:
            context = _build_fake_context(
                str(sample_png_path),
                staging,
                "md",
                {
                    "image_mode": "file",
                    "ocr_placement": "image_md",
                    "to_md_enable_ocr": True,
                    "to_md_keep_images": True,
                },
                config_snapshot={"link": {"format": {"md_file_link_style": "wiki_link"}}},
            )
            result = ImageToMarkdownConverter().convert(context)

            assert result.success is True
            primary_md = Path(next(a for a in result.artifacts if a.kind == "primary").staging_path).read_text(
                encoding="utf-8"
            )
            assert "[[sample_ocr.md]]" in primary_md
            # Must NOT have ! prefix (wiki_link, not wiki_embed)
            assert "![[sample_ocr.md]]" not in primary_md

    def test_md_file_link_style_markdown_link(self, sample_png_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """``markdown_link`` produces ``[file.md](file.md)`` for the
        auxiliary .md."""
        import docwen_plugin_image.to_markdown.converter as converter_mod
        from docwen_plugin_image.to_markdown.converter import (
            ImageToMarkdownConverter,
        )

        monkeypatch.setattr(converter_mod, "run_ocr_outcome", lambda _path, **_kwargs: _ocr_success("markdown链接"))

        with tempfile.TemporaryDirectory() as staging:
            context = _build_fake_context(
                str(sample_png_path),
                staging,
                "md",
                {
                    "image_mode": "file",
                    "ocr_placement": "image_md",
                    "to_md_enable_ocr": True,
                    "to_md_keep_images": True,
                },
                config_snapshot={"link": {"format": {"md_file_link_style": "markdown_link"}}},
            )
            result = ImageToMarkdownConverter().convert(context)

            assert result.success is True
            primary_md = Path(next(a for a in result.artifacts if a.kind == "primary").staging_path).read_text(
                encoding="utf-8"
            )
            assert "[sample_ocr.md](sample_ocr.md)" in primary_md
            assert "![[sample_ocr.md]]" not in primary_md
            assert "[[sample_ocr.md]]" not in primary_md

    def test_md_file_link_style_markdown_embed_falls_back_to_link(
        self, sample_png_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """``markdown_embed`` for .md files falls back to
        ``[file.md](file.md)`` (cannot natively embed .md)."""
        import docwen_plugin_image.to_markdown.converter as converter_mod
        from docwen_plugin_image.to_markdown.converter import (
            ImageToMarkdownConverter,
        )

        monkeypatch.setattr(
            converter_mod,
            "run_ocr_outcome",
            lambda _path, **_kwargs: _ocr_success("markdown嵌入fallback"),
        )

        with tempfile.TemporaryDirectory() as staging:
            context = _build_fake_context(
                str(sample_png_path),
                staging,
                "md",
                {
                    "image_mode": "file",
                    "ocr_placement": "image_md",
                    "to_md_enable_ocr": True,
                    "to_md_keep_images": True,
                },
                config_snapshot={"link": {"format": {"md_file_link_style": "markdown_embed"}}},
            )
            result = ImageToMarkdownConverter().convert(context)

            assert result.success is True
            primary_md = Path(next(a for a in result.artifacts if a.kind == "primary").staging_path).read_text(
                encoding="utf-8"
            )
            # markdown_embed falls back to markdown_link for .md files
            assert "[sample_ocr.md](sample_ocr.md)" in primary_md
            assert "![[sample_ocr.md]]" not in primary_md


class TestFormatMdFileLink:
    """Verify the shared ``format_md_file_link`` utility (F-G1-005, F-G2-003)."""

    def test_format_md_file_link_wiki_embed(self) -> None:
        from docwen_core.markdown_utils import format_md_file_link

        result = format_md_file_link("report.md", style="wiki_embed")
        assert result == "![[report.md]]"

    def test_format_md_file_link_wiki_link(self) -> None:
        from docwen_core.markdown_utils import format_md_file_link

        result = format_md_file_link("report.md", style="wiki_link")
        assert result == "[[report.md]]"

    def test_format_md_file_link_markdown_link(self) -> None:
        from docwen_core.markdown_utils import format_md_file_link

        result = format_md_file_link("report.md", style="markdown_link")
        assert result == "[report.md](report.md)"

    def test_format_md_file_link_markdown_embed_falls_back(self) -> None:
        from docwen_core.markdown_utils import format_md_file_link

        result = format_md_file_link("report.md", style="markdown_embed")
        assert result == "[report.md](report.md)"

    def test_format_md_file_link_sanitizes_wiki_sensitive_chars(self) -> None:
        from docwen_core.markdown_utils import format_md_file_link

        result = format_md_file_link("file[name].md", style="wiki_embed")
        assert "[" not in result.replace("!", "").replace("[[", "").replace("]]", "")
        assert "filenamemd" in result.lower().replace(".", "").replace("!", "").replace("[", "").replace("]", "")

    def test_format_md_file_link_sanitizes_fs_illegal_chars(self) -> None:
        from docwen_core.markdown_utils import format_md_file_link

        result = format_md_file_link("file:name.md", style="markdown_link")
        assert ":" not in result

    def test_format_md_file_link_unknown_style_falls_back(self) -> None:
        from docwen_core.markdown_utils import format_md_file_link

        result = format_md_file_link("doc.md", style="unknown")
        assert result == "![[doc.md]]"  # falls back to wiki_embed
