ERROR_CODE_UNKNOWN_ERROR = "unknown_error"
ERROR_CODE_CONVERSION_FAILED = "conversion_failed"
ERROR_CODE_INVALID_INPUT = "invalid_input"
ERROR_CODE_DEPENDENCY_MISSING = "dependency_missing"
ERROR_CODE_OPERATION_CANCELLED = "operation_cancelled"
ERROR_CODE_NOT_IMPLEMENTED = "not_implemented"
ERROR_CODE_UNSUPPORTED_FORMAT = "unsupported_format"
ERROR_CODE_SKIPPED_SAME_FORMAT = "skipped_same_format"
ERROR_CODE_STRATEGY_NOT_FOUND = "strategy_not_found"
ERROR_CODE_SECURITY_CHECK_FAILED = "security_check_failed"

KNOWN_ERROR_CODES: set[str] = {
    ERROR_CODE_UNKNOWN_ERROR,
    ERROR_CODE_CONVERSION_FAILED,
    ERROR_CODE_INVALID_INPUT,
    ERROR_CODE_DEPENDENCY_MISSING,
    ERROR_CODE_OPERATION_CANCELLED,
    ERROR_CODE_NOT_IMPLEMENTED,
    ERROR_CODE_UNSUPPORTED_FORMAT,
    ERROR_CODE_SKIPPED_SAME_FORMAT,
    ERROR_CODE_STRATEGY_NOT_FOUND,
    ERROR_CODE_SECURITY_CHECK_FAILED,
}
