"""MathML to LaTeX conversion."""

from __future__ import annotations

import logging
import re

import lxml.etree as etree

from docwen_core.formula.constants import NARY_OP_MAP, SYMBOL_MAP

logger = logging.getLogger(__name__)


def _clean_matrix_brackets(latex_str: str) -> str:
    r"""Clean duplicate brackets around matrix environments.

    Handles documents generated by software like WPS that may produce:
    - [\begin{bmatrix} -> \begin{bmatrix}
    - \end{bmatrix}] -> \end{bmatrix}
    etc.
    """
    latex_str = re.sub(r"\[\\begin\{bmatrix\}", r"\\begin{bmatrix}", latex_str)
    latex_str = re.sub(r"\\end\{bmatrix\}\]", r"\\end{bmatrix}", latex_str)

    latex_str = re.sub(r"\(\\begin\{pmatrix\}", r"\\begin{pmatrix}", latex_str)
    latex_str = re.sub(r"\\end\{pmatrix\}\)", r"\\end{pmatrix}", latex_str)

    latex_str = re.sub(r"\|\\begin\{vmatrix\}", r"\\begin{vmatrix}", latex_str)
    latex_str = re.sub(r"\\end\{vmatrix\}\|", r"\\end{vmatrix}", latex_str)

    latex_str = re.sub(r"\|\|\\begin\{Vmatrix\}", r"\\begin{Vmatrix}", latex_str)
    latex_str = re.sub(r"\\end\{Vmatrix\}\|\|", r"\\end{Vmatrix}", latex_str)

    latex_str = re.sub(r"\{\\begin\{Bmatrix\}", r"\\begin{Bmatrix}", latex_str)
    latex_str = re.sub(r"\\end\{Bmatrix\}\}", r"\\end{Bmatrix}", latex_str)

    return latex_str


def _find_mtable_descendant(elem):
    """Find mtable element anywhere in the subtree."""
    elem_tag = etree.QName(elem).localname
    if elem_tag == "mtable":
        return elem
    for child in elem:
        result = _find_mtable_descendant(child)
        if result is not None:
            return result
    return None


def _convert_matrix_rows(mtable_elem) -> str:
    """Convert mtable element to LaTeX matrix rows."""
    rows: list[str] = []
    for mtr_elem in mtable_elem:
        if etree.QName(mtr_elem).localname == "mtr":
            cells: list[str] = []
            for mtd_elem in mtr_elem:
                if etree.QName(mtd_elem).localname == "mtd":
                    cell_content = "".join([_mathml_node_to_latex(c) for c in mtd_elem]).strip()
                    cells.append(cell_content)
            if cells:
                rows.append(" & ".join(cells))
    return " \\\\\n".join(rows)


def _detect_matrix_from_bracket_markers(
    children: list,
    start_idx: int,
    parts: list,
    level_name: str = "node",
) -> tuple[int, bool]:
    """Detect mo/matrix/mo bracket patterns and convert to LaTeX matrix.

    Checks if children[i] is a bracket mo, children[i+1] contains an mtable,
    and children[i+2] is the matching closing mo.

    Returns (advance_count, handled).
    """
    if start_idx + 2 >= len(children):
        return 0, False

    curr_tag = etree.QName(children[start_idx]).localname
    next_tag = etree.QName(children[start_idx + 2]).localname

    if curr_tag != "mo" or next_tag != "mo":
        return 0, False

    curr_text = (children[start_idx].text or "").strip()
    next_text = (children[start_idx + 2].text or "").strip()

    middle_child = children[start_idx + 1]
    matrix_elem = _find_mtable_descendant(middle_child)

    if matrix_elem is None:
        return 0, False

    # Determine matrix type from brackets
    matrix_type: str | None = None
    if curr_text == "[" and (next_text == "]" or next_text.startswith("]")):
        matrix_type = "bmatrix"
        logger.debug(f"{level_name} level detected [matrix] pattern, using bmatrix")
    elif curr_text == "(" and (next_text == ")" or next_text.startswith(")")):
        matrix_type = "pmatrix"
        logger.debug(f"{level_name} level detected (matrix) pattern, using pmatrix")
    elif curr_text == "|" and (next_text == "|" or next_text.startswith("|")):
        matrix_type = "vmatrix"
        logger.debug(f"{level_name} level detected |matrix| pattern, using vmatrix")

    if matrix_type is None:
        return 0, False

    matrix_content = _convert_matrix_rows(matrix_elem)
    if matrix_content:
        result = f"\\begin{{{matrix_type}}}\n{matrix_content}\n\\end{{{matrix_type}}}"
        parts.append(result)
        logger.debug(f"{level_name} level successfully converted matrix: {matrix_type}")
        return 3, True

    return 0, False


def _mathml_node_to_latex(node) -> str:
    """Recursively convert MathML node to LaTeX."""
    tag = etree.QName(node).localname

    if tag == "math":
        children = list(node)
        parts: list[str] = []
        i = 0
        while i < len(children):
            handled_end_idx, handled = _detect_matrix_from_bracket_markers(children, i, parts, level_name="math")
            if handled:
                i += handled_end_idx
                continue
            parts.append(_mathml_node_to_latex(children[i]))
            i += 1
        return "".join(parts)

    elif tag in ("mi", "mn", "mo"):
        text = node.text or ""
        return SYMBOL_MAP.get(text, text)

    elif tag == "mfrac":
        children = list(node)
        if len(children) >= 2:
            num = _mathml_node_to_latex(children[0]).strip()
            den = _mathml_node_to_latex(children[1]).strip()
            return f"\\frac{{{num}}}{{{den}}}"
        return ""

    elif tag == "msup":
        children = list(node)
        if len(children) >= 2:
            base = _mathml_node_to_latex(children[0]).strip()
            sup = _mathml_node_to_latex(children[1]).strip()
            if len(base) == 1 or base in NARY_OP_MAP.values():
                return f"{base}^{{{sup}}}"
            return f"{{{base}}}^{{{sup}}}"
        return ""

    elif tag == "msub":
        children = list(node)
        if len(children) >= 2:
            base = _mathml_node_to_latex(children[0]).strip()
            sub = _mathml_node_to_latex(children[1]).strip()
            if len(base) == 1 or base in NARY_OP_MAP.values():
                return f"{base}_{{{sub}}}"
            return f"{{{base}}}_{{{sub}}}"
        return ""

    elif tag == "msubsup":
        children = list(node)
        if len(children) >= 3:
            base = _mathml_node_to_latex(children[0]).strip()
            sub = _mathml_node_to_latex(children[1]).strip()
            sup = _mathml_node_to_latex(children[2]).strip()
            if base in NARY_OP_MAP.values() or len(base) == 1:
                return f"{base}_{{{sub}}}^{{{sup}}}"
            else:
                return f"{{{base}}}_{{{sub}}}^{{{sup}}}"
        return ""

    elif tag == "munderover":
        children = list(node)
        if len(children) >= 3:
            base = _mathml_node_to_latex(children[0]).strip()
            under = _mathml_node_to_latex(children[1]).strip()
            over = _mathml_node_to_latex(children[2]).strip()
            return f"{base}_{{{under}}}^{{{over}}}"
        return ""

    elif tag == "munder":
        children = list(node)
        if len(children) >= 2:
            base = _mathml_node_to_latex(children[0]).strip()
            under = _mathml_node_to_latex(children[1]).strip()
            return f"{base}_{{{under}}}"
        return ""

    elif tag == "msqrt":
        content = "".join([_mathml_node_to_latex(child) for child in node]).strip()
        return f"\\sqrt{{{content}}}"

    elif tag == "mroot":
        children = list(node)
        if len(children) >= 2:
            base = _mathml_node_to_latex(children[0]).strip()
            deg = _mathml_node_to_latex(children[1]).strip()
            return f"\\sqrt[{deg}]{{{base}}}"
        return ""

    elif tag == "mrow":
        children = list(node)
        parts: list[str] = []
        i = 0

        while i < len(children):
            handled_end_idx, handled = _detect_matrix_from_bracket_markers(children, i, parts, level_name="mrow")
            if handled:
                i += handled_end_idx
                continue

            child = children[i]
            child_tag = etree.QName(child).localname
            part = _mathml_node_to_latex(child)

            if part:
                need_space_before = False
                if i > 0 and parts:
                    prev_part = parts[-1].strip() if parts else ""
                    current_part = part.strip()

                    if (
                        child_tag == "mo"
                        and current_part
                        in [
                            "+",
                            "-",
                            "=",
                            "<",
                            ">",
                            "\\times",
                            "\\div",
                            "\\pm",
                            "\\leq",
                            "\\geq",
                            "\\neq",
                            "\\approx",
                        ]
                        and prev_part
                        and not prev_part.endswith(" ")
                    ):
                        need_space_before = True

                    if i > 0:
                        prev_child = children[i - 1]
                        prev_tag = etree.QName(prev_child).localname
                        if prev_tag == "mo" and child_tag != "mo":
                            prev_text = prev_child.text or ""
                            if (
                                prev_text.strip() in ["+", "-", "=", "<", ">", "×", "÷", "±", "≤", "≥", "≠", "≈"]
                                and prev_part
                                and not prev_part.endswith(" ")
                            ):
                                need_space_before = True

                if need_space_before:
                    parts.append(" ")
                    logger.debug("Added space around operator")

                parts.append(part)

            i += 1

        return "".join(parts)

    elif tag == "mtable":
        matrix_content = _convert_matrix_rows(node)
        if matrix_content:
            return f"\\begin{{bmatrix}}\n{matrix_content}\n\\end{{bmatrix}}"
        return ""

    elif tag == "mfenced":
        open_char = node.get("open", "(")
        close_char = node.get("close", ")")

        logger.debug(f"Processing mfenced tag, bracket type: {open_char}...{close_char}")

        has_mtable = _find_mtable_descendant(node) is not None

        if has_mtable:
            logger.debug(f"Matrix detected inside mfenced, brackets: {open_char}...{close_char}")

            # Map bracket chars to matrix environment
            matrix_type: str
            if open_char == "[" and close_char == "]":
                matrix_type = "bmatrix"
            elif open_char == "(" and close_char == ")":
                matrix_type = "pmatrix"
            elif open_char == "|" and close_char == "|":
                matrix_type = "vmatrix"
            elif open_char in ("||", "‖") and close_char in ("||", "‖"):
                matrix_type = "Vmatrix"
            elif open_char == "{" and close_char == "}":
                matrix_type = "Bmatrix"
            else:
                matrix_type = "matrix"

            logger.debug(f"Selected matrix type: {matrix_type}")

            mtable = _find_mtable_descendant(node)
            if mtable is not None:
                matrix_content = _convert_matrix_rows(mtable)
                if matrix_content:
                    result = f"\\begin{{{matrix_type}}}\n{matrix_content}\n\\end{{{matrix_type}}}"
                    logger.debug(f"Matrix conversion succeeded: {matrix_type}")
                    return result
                else:
                    logger.warning("Matrix row extraction failed, returning empty matrix")
                    return f"\\begin{{{matrix_type}}}\n\\end{{{matrix_type}}}"
            else:
                logger.warning("mtable element not found, returning empty matrix")
                return f"\\begin{{{matrix_type}}}\n\\end{{{matrix_type}}}"

        logger.debug("mfenced does not contain a matrix, treating as plain brackets")
        content = "".join([_mathml_node_to_latex(child) for child in node])
        return f"{open_char}{content}{close_char}"

    else:
        # Unknown tag: recurse into children
        return "".join([_mathml_node_to_latex(child) for child in node])


def mathml_to_latex(mathml_str: str) -> str | None:
    """Convert MathML to LaTeX format.

    Args:
        mathml_str: MathML XML string.

    Returns:
        LaTeX string, or None if conversion fails.
    """
    try:
        mathml_tree = etree.fromstring(mathml_str.encode("utf-8"))
        result = _mathml_node_to_latex(mathml_tree)

        if result:
            result = _clean_matrix_brackets(result)

        return result
    except Exception as e:
        logger.error(f"MathML to LaTeX failed: {e}")
        return None
