# ==============================================================================
#  校对括号配对配置
# ==============================================================================

items = [
    ["(", ")"],
    ["（", "）"],
    ["[", "]"],
    ["【", "】"],
    ["{", "}"],
    ["「", "」"],
    ["'", "'"],
    ["\"", "\""],
    ["‘", "’"],
    ["“", "”"],
    ["《", "》"],
]
